sudo: required

services:
    - docker

before_install:
    - docker build -t vballa/loginapp .

script:
    - docker run vballa/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push vballa/loginapp

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: dockerloginapp
    env: Dockerloginapp-env
    bucket_name: elasticbeanstalk-us-east-2-221353196223
    bucket_path: dockerloginapp
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
