sudo: required

services:
    - docker

before_install:
    - docker build -t vballa/loginapp .

script:
    - docker run vballa/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push vballa/loginapp

# deploy:
#     provider: elasticbeanstalk
#     region: ap-south-1
#     app: docker-loginapp
#     env: DockerLoginapp-env
#     bucket_name: elasticbeanstalk-ap-south-1-679022722124
#     bucket_path: docker-loginapp
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_acces_key: $AWS_SECRET_KEY
